### PR TITLE
Pr/update module trailmaking test

### PR DESCRIPTION
**Pull request by faraz-hussain**
Fixes line misalignments when rotating display, and adds timer and error scores.

### CODE REVIEW

**Comment by syoung-smallwisdom** [comment]
@faraz-hussain 
Could you please update https://github.com/ResearchKit/ResearchKit/pull/880 and ping me with those changes?

Because we are attempting to keep parity with ResearchKit/ResearchKit (for now), I have to manually track all the branches with pull requests to RK that we are pulling into Sage. I notice that you have a commit here 	039b603 that isn't in that pull request.  Thanks

**Comment by faraz-hussain** [comment]
@syoung-smallwisdom 
[ResearchKit#880](https://github.com/ResearchKit/ResearchKit/pull/880) has already been updated with each of these changes.

https://github.com/Sage-Bionetworks/ResearchKit/commit/039b6033a1088157bf354f9f1f84fcd4ad99b834 is equivalent to https://github.com/ResearchKit/ResearchKit/pull/880/commits/0a2c937ef24211f26489750244585bad380df09f

**Comment by syoung-smallwisdom** [comment]
cool, thanks for clarifying.

**Comment by syoung-smallwisdom** [comment]
Pushed to BridgeAppSDK.

**Pull request closed without merging**
